// Generated by scripts/generate-loop-event-contracts.mjs.
// Do not edit manually.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum DiagnosticCategory {
    #[serde(rename = "model")]
    Model,
    #[serde(rename = "mechanical")]
    Mechanical,
    #[serde(rename = "validator")]
    Validator,
    #[serde(rename = "gate")]
    Gate,
    #[serde(rename = "info")]
    Info,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum DiagnosticSeverity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warn")]
    Warn,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "fatal")]
    Fatal,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ObligationStatus {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "closed_proved")]
    ClosedProved,
    #[serde(rename = "closed_refuted")]
    ClosedRefuted,
    #[serde(rename = "closed_spurious")]
    ClosedSpurious,
    #[serde(rename = "demoted")]
    Demoted,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SatisfactionSource {
    #[serde(rename = "solver")]
    Solver,
    #[serde(rename = "reviewer")]
    Reviewer,
    #[serde(rename = "adversary")]
    Adversary,
    #[serde(rename = "mechanical")]
    Mechanical,
    #[serde(rename = "checkpoint_reviewer")]
    CheckpointReviewer,
    #[serde(rename = "checkpoint_adversary")]
    CheckpointAdversary,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SidecarWarmupStatus {
    #[serde(rename = "waiting")]
    Waiting,
    #[serde(rename = "warming")]
    Warming,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "timeout")]
    Timeout,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ScoutTrigger {
    #[serde(rename = "pre_solve")]
    PreSolve,
    #[serde(rename = "mid_solve")]
    MidSolve,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum DiscernerClassification {
    #[serde(rename = "mechanical")]
    Mechanical,
    #[serde(rename = "model")]
    Model,
    #[serde(rename = "gate")]
    Gate,
    #[serde(rename = "validator")]
    Validator,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum DiscernerSuggestedAction {
    #[serde(rename = "switch_model")]
    SwitchModel,
    #[serde(rename = "add_backoff")]
    AddBackoff,
    #[serde(rename = "retry")]
    Retry,
    #[serde(rename = "rephrase_prompt")]
    RephrasePrompt,
    #[serde(rename = "continue")]
    Continue,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct EmptyPayload {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopStartedData {
    pub problem: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ReviewFinding {
    #[serde(rename = "type")]
    pub type_: String,
    pub summary: String,
    pub detail: String,
    pub priority: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AuditResult {
    pub step_number: u32,
    pub breadth: f64,
    pub techniques_explored: Vec<String>,
    pub techniques_missing: Vec<String>,
    pub recommended_direction: String,
    pub should_branch: bool,
    pub confidence: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ReviewResult {
    pub attempt_id: String,
    pub findings_count: u32,
    pub exploration_coverage: f64,
    pub conclusion_sound: bool,
    pub conclusion_confidence: f64,
    pub training_label: String,
    pub missing_constructions: Vec<String>,
    pub findings: Vec<ReviewFinding>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manual: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub problem_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ExtractedPattern {
    pub name: String,
    pub description: String,
    pub trigger_text: String,
    pub strategy: String,
    pub technique_class: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ObligationSignal {
    pub source: String,
    pub satisfies: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ObligationEvent {
    pub id: String,
    pub description: String,
    pub obligation_type: String,
    pub priority: f64,
    pub status: ObligationStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_by_step: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closure_note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assigned_model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub steps_spent: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_steps: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tally_yes: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tally_total: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signals: Option<Vec<ObligationSignal>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assigned_models: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_solver_round_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dispatch_mode: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SatisfactionSignalEvent {
    pub obligation_id: String,
    pub source: SatisfactionSource,
    pub satisfies: bool,
    pub tally_yes: u32,
    pub tally_total: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CriticCheckEvent {
    pub obligation_id: String,
    pub check_description: String,
    pub expected_if_correct: String,
    pub counterexample_hint: String,
    pub likely_wrong: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DiscernerFinding {
    pub attempt_id: String,
    pub step_number: u32,
    pub failure_streak: u32,
    pub classification: DiscernerClassification,
    pub root_cause: String,
    pub recommendation: String,
    pub confidence: f64,
    pub suggested_action: DiscernerSuggestedAction,
    pub discerner_model: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DiagnosticEvent {
    pub ts: String,
    pub category: DiagnosticCategory,
    pub severity: DiagnosticSeverity,
    pub source: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub step_number: Option<u32>,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempt_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopStartedPayload {
    pub event: String,
    pub attempt_id: String,
    pub data: LoopStartedData,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopThinkingStartPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub step_number: Option<u32>,
    pub model: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_role: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub review: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manual: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopTokenPayload {
    pub text: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_role: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopThinkingEndPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ClaimEventRecord {
    pub raw: String,
    pub formal: String,
    pub source: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopStepCompletePayload {
    pub attempt_id: String,
    pub step_number: u32,
    pub proposal_type: String,
    pub proposal_natural: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proposal_formal: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proposal_reasoning: Option<String>,
    pub verified: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejection_reason: Option<String>,
    pub model: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sympy_passed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pint_passed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lean_passed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub challenge_model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub challenge_flaw_found: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub challenge_attack: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub challenge_confidence: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub challenge_fatal: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solver_round_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solver_worker_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solver_dispatch_mode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stale_sibling: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopAttemptStartPayload {
    pub attempt_id: String,
    pub attempt_number: u32,
    pub max_attempts: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub constraints: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopRetryPayload {
    pub attempt_number: u32,
    pub max_attempts: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_attempt_id: Option<String>,
    pub new_attempt_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopOuterCompletePayload {
    pub attempts_used: u32,
    pub final_attempt_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopFinishedPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempt_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopReviewStartPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempt_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manual: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub problem_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopSidecarWarmupPayload {
    pub status: SidecarWarmupStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopObligationOpenedPayload {
    pub id: String,
    pub description: String,
    pub obligation_type: String,
    pub priority: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decomposition_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopObligationClosedPayload {
    pub id: String,
    pub status: ObligationStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closure_node_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_by_step: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closure_note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tally_yes: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tally_total: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopObligationAssignedPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempt_id: Option<String>,
    pub obligation_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<f64>,
    pub assigned_model: String,
    pub steps_spent: u32,
    pub max_steps: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dispatch_mode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worker_count: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub blacklisted_approaches: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopPivotForcedPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempt_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_id: Option<String>,
    pub obligation_desc: String,
    pub blacklisted_technique: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopDecompositionStartPayload {
    pub attempt_id: String,
    pub trigger: String,
    pub model: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopDecompositionCompletePayload {
    pub attempt_id: String,
    pub decomposition_id: String,
    pub obligations_created: u32,
    pub problem_type: String,
    pub model: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopContradictionDetectedPayload {
    pub obligation_id: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopObligationGatePayload {
    pub step_number: u32,
    pub open_count: u32,
    pub obligations: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopPatternsExtractedPayload {
    pub attempt_id: String,
    pub count: u32,
    pub patterns: Vec<ExtractedPattern>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopErrorPayload {
    pub message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopNodeChallengedPayload {
    pub step_number: u32,
    pub adversary_model: String,
    pub flaw_found: bool,
    pub attack_vector: String,
    pub confidence: f64,
    pub fatal: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suggested_fix: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopConclusionReviewPayload {
    pub step_number: u32,
    pub sound: bool,
    pub confidence: f64,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopFaninRoundStartPayload {
    pub attempt_id: String,
    pub solver_round_id: String,
    pub obligation_id: String,
    pub obligation_desc: String,
    pub worker_count: u32,
    pub worker_models: Vec<String>,
    pub reserved_step_numbers: Vec<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopFaninRoundUpdatePayload {
    pub solver_round_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub step_number: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopFaninRoundCompletePayload {
    pub solver_round_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workers_dispatched: Option<u32>,
    pub results_processed: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results_skipped_stale: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub early_exit: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopSolverSelfAssessmentPayload {
    pub step_number: u32,
    pub targets_obligation: String,
    pub closes_obligation: bool,
    pub closure_reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopStepErrorPayload {
    pub step_number: u32,
    pub error_type: String,
    pub model: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempt_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopToolCallPayload {
    pub step_number: u32,
    pub tool: String,
    pub input: serde_json::Value,
    pub result: String,
    pub result_len: u32,
    pub tool_calls_made: u32,
    pub latency_ms: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopClaimCheckFailedPayload {
    pub step_number: u32,
    pub claim_type: String,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopSympyCorrectionAttemptPayload {
    pub step_number: u32,
    pub original_formal: String,
    pub diff: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopSympyCorrectionAppliedPayload {
    pub step_number: u32,
    pub original: String,
    pub corrected: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopSuspectedAnswerDisprovedPayload {
    pub step_number: u32,
    pub suspected_value: String,
    pub source: String,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopClaimsExtractedPayload {
    pub step_number: u32,
    pub claims: Vec<ClaimEventRecord>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopObligationBlockedPayload {
    pub description: String,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audit_session_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopBranchCreatedPayload {
    pub branch_id: u32,
    pub parent_branch: u32,
    pub fork_reason: String,
    pub direction: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopBranchClosedPayload {
    pub branch_id: u32,
    pub status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopBranchSwitchedPayload {
    pub from_branch: u32,
    pub to_branch: u32,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopEvidenceCollapsePayload {
    pub step_number: u32,
    pub collapsed_count: u32,
    pub evidence_bound: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopAnswerMismatchPayload {
    pub step_number: u32,
    pub proposed_answer: String,
    pub known_answer: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopClaimConflictPayload {
    pub step_number: u32,
    pub conflict: String,
    pub claims: Vec<ClaimEventRecord>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LoopCheckpointStartPayload {
    pub step_number: u32,
    pub open_obligations: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentOrchestratorEventPayload {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligations_created: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub problem_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worker_count: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worker_models: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results_processed: Option<u32>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentCriticEvaluationPayload {
    pub obligation_id: String,
    pub check_description: String,
    pub likely_wrong: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentCouncilFindingPayload {
    pub obligation_id: String,
    pub tally_yes: u32,
    pub tally_total: u32,
    pub outcome: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentScoutResultPayload {
    pub trigger: ScoutTrigger,
    pub results_count: u32,
    pub sources: Vec<String>,
    pub briefing: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub obligation_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub blacklisted_techniques: Option<Vec<String>>,
}
