use crate::models::dag::Obligation;
use serde::Deserialize;

/// A concrete counterexample check generated by the adversarial critic.
#[derive(Debug, Clone, Deserialize)]
pub struct CriticCheck {
    /// What specific computation or verification to perform
    pub check_description: String,
    /// What the result should be if the solver's current approach is correct
    #[serde(default)]
    pub expected_if_correct: String,
    /// A specific small case or counterexample to test
    #[serde(default)]
    pub counterexample_hint: String,
    /// Whether the critic believes the current approach is likely wrong
    #[serde(default)]
    pub likely_wrong: bool,
}

/// Build a critic prompt that generates a concrete counterexample check for an obligation.
///
/// The critic takes a high-priority obligation and the verified chain, then proposes
/// a specific, concrete check (e.g. "compute f(4) for permutation (2,4,1,3)").
pub fn build_critic_prompt(
    problem: &str,
    obligation: &Obligation,
    verified_chain: &[(String, u32, String, String, String)],
    research_context: &str,
    suspected_answer: Option<&str>,
) -> String {
    let mut p = String::from(
        "You are an adversarial critic. Your job is to find COUNTEREXAMPLES that break \
the solver's current approach.\n\n\
You are given a proof obligation — something the solver MUST check — and the \
verified chain so far. Generate a SPECIFIC, CONCRETE check that could falsify \
the solver's approach.\n\n\
The best checks are:\n\
- Small cases (n=3, n=4, n=5) with specific parameter values\n\
- Non-trivial instances that the solver might have skipped\n\
- Edge cases that break common patterns\n\n",
    );

    // Inject enriched context (prior attempts, research, pattern stats)
    if !research_context.is_empty() {
        p.push_str(research_context);
        p.push('\n');
    }

    p.push_str(&format!("PROBLEM: {}\n\n", problem));

    if let Some(answer) = suspected_answer {
        p.push_str(&format!(
            "SUSPECTED ANSWER: {} — use this to craft targeted counterexamples.\n\n",
            answer
        ));
    }

    p.push_str(&format!("OBLIGATION: {}\n", obligation.description));
    p.push_str(&format!("  Type: {}\n", obligation.obligation_type));
    if let Some(ref criteria) = obligation.satisfaction_criteria {
        p.push_str(&format!("  Satisfied when: {}\n", criteria));
    }
    p.push('\n');

    if !verified_chain.is_empty() {
        p.push_str(&format!(
            "VERIFIED CHAIN ({} steps):\n",
            verified_chain.len()
        ));
        for (_, n, _, nat, formal) in verified_chain {
            p.push_str(&format!("  Step {}: {} [formal: {}]\n", n, nat, formal));
        }
        p.push('\n');
    }

    p.push_str(
"Generate a specific counterexample check. Respond with ONLY a JSON object (no markdown fences):\n\
{\n\
  \"check_description\": \"exactly what computation to perform — be specific enough that it can be carried out\",\n\
  \"expected_if_correct\": \"what the result should be IF the solver's current approach is right\",\n\
  \"counterexample_hint\": \"specific values/parameters to test (e.g. 'n=4, σ=(2,4,1,3)')\",\n\
  \"likely_wrong\": true if you believe the solver's approach has a flaw that this check will expose\n\
}");
    p
}

/// Result of an adversarial node challenge — a non-familial model tries to
/// find a flaw in a verified proof step.
#[derive(Debug, Clone, Deserialize)]
pub struct NodeChallenge {
    /// Whether the challenger found a flaw.
    #[serde(default)]
    pub flaw_found: bool,
    /// The specific attack vector or flaw description.
    #[serde(default)]
    pub attack_vector: String,
    /// Confidence the challenger has in its assessment (0.0-1.0).
    /// When flaw_found=false, this is confidence the step is correct.
    #[serde(default)]
    pub confidence: f64,
    /// Suggested fix or direction if a flaw was found.
    #[serde(default)]
    pub suggested_fix: String,
    /// Whether this is a fatal flaw (should reject the node) or a minor concern.
    #[serde(default)]
    pub fatal: bool,
    /// Reasoning for the verdict — ALWAYS populated, explains why the step
    /// passes or fails the adversarial check.
    #[serde(default)]
    pub reasoning: String,
}

/// Build a node challenge prompt — an adversarial attack on a specific verified step.
/// This must be run by a DIFFERENT model family than the one that produced the step.
pub fn build_node_challenge_prompt(
    problem: &str,
    step_natural: &str,
    step_formal: Option<&str>,
    step_reasoning: Option<&str>,
    verified_chain: &[(String, u32, String, String, String)],
    solver_model: &str,
    research_context: &str,
    target_obligation: Option<&Obligation>,
    validation_summary: &str,
) -> String {
    let mut p = format!(
        "You are an adversarial challenger. A solver ({}) produced a proof step. \
Your job is to ATTACK it — find any flaw, gap, or unjustified leap.\n\n\
You are from a DIFFERENT model family than the solver. This is intentional: \
models from the same family share systematic blind spots. Your fresh perspective \
is the entire point.\n\n\
ATTACK VECTORS TO CHECK:\n\
1. Does the formal expression actually capture the natural language claim?\n\
2. Is there an implicit assumption that hasn't been justified?\n\
3. Does this step follow from the previous verified steps, or is there a logical gap?\n\
4. Are there counterexamples that would break this claim?\n\
5. Is the step trivially true but irrelevant to the actual problem?\n\
6. Could the claim be true for the wrong reason (coincidental correctness)?\n\n",
        solver_model
    );

    // Inject enriched context (prior attempts, research, pattern stats)
    if !research_context.is_empty() {
        p.push_str(research_context);
        p.push('\n');
    }

    p.push_str(&format!("PROBLEM: {}\n\n", problem));

    // Target obligation context (if this step is addressing one)
    if let Some(ob) = target_obligation {
        p.push_str(&format!(
            "TARGET OBLIGATION: [{}] {}\n",
            ob.obligation_type, ob.description
        ));
        if let Some(ref criteria) = ob.satisfaction_criteria {
            p.push_str(&format!("  Satisfied when: {}\n", criteria));
        }
        p.push_str("  Attack angle: Does this step actually advance toward satisfying this obligation?\n\n");
    }

    // Validation results (what the mechanical validators found)
    if !validation_summary.is_empty() {
        p.push_str(&format!("VALIDATION RESULTS: {}\n\n", validation_summary));
    }

    p.push_str("STEP UNDER ATTACK:\n");
    p.push_str(&format!("  Natural: {}\n", step_natural));
    if let Some(f) = step_formal {
        p.push_str(&format!("  Formal:  {}\n", f));
    }
    if let Some(r) = step_reasoning {
        p.push_str(&format!("  Reasoning: {}\n", r));
    }
    p.push('\n');

    if !verified_chain.is_empty() {
        p.push_str(&format!(
            "PRIOR VERIFIED CHAIN ({} steps):\n",
            verified_chain.len()
        ));
        for (_, n, _, nat, formal) in verified_chain {
            p.push_str(&format!("  Step {}: {} [formal: {}]\n", n, nat, formal));
        }
        p.push('\n');
    }

    p.push_str(
"Your attack must be SPECIFIC — not vague concerns. Name exact counterexamples, \
exact logical gaps, exact unjustified assumptions.\n\n\
IMPORTANT: Reason FIRST, then decide. Do not commit to a verdict until you have \
fully analyzed the step. You are allowed to change your mind during analysis.\n\n\
Respond with ONLY a JSON object (no markdown fences).\n\
CRITICAL: The fields MUST appear in this order — reasoning first, verdict last:\n\
{\n\
  \"reasoning\": \"your full analysis — what you checked, what you found, why. ALWAYS fill this in.\",\n\
  \"attack_vector\": \"specific description of the flaw — what exactly is wrong and why (empty if no flaw)\",\n\
  \"suggested_fix\": \"how the solver should fix this (empty if no flaw)\",\n\
  \"confidence\": 0.0-1.0 (how confident you are in your FINAL verdict after reasoning),\n\
  \"flaw_found\": true/false (YOUR FINAL VERDICT — decide this AFTER your reasoning, not before),\n\
  \"fatal\": true if this flaw invalidates the step entirely, false if minor or no flaw\n\
}");
    p
}

/// Parse a node challenge response from LLM text.
pub fn parse_node_challenge(response: &str) -> Option<NodeChallenge> {
    super::json_parse::extract_json(response)
}

/// Determine the model family from a model name string (e.g. "anthropic/claude-sonnet-4-6" → "anthropic").
pub fn model_family(model_name: &str) -> &str {
    model_name.split('/').next().unwrap_or(model_name)
}

/// Check if two models are from different families (non-familial).
pub fn is_non_familial(model_a: &str, model_b: &str) -> bool {
    model_family(model_a) != model_family(model_b)
}

/// Parse a critic response from LLM text.
pub fn parse_critic(response: &str) -> Option<CriticCheck> {
    super::json_parse::extract_json(response)
}

/// Build a prompt for the adversary to challenge satisfaction claims.
/// The adversary is naturally skeptical — it looks for gaps in the cumulative work.
/// Returns prompt text. Output should be JSON: [{"id": "...", "satisfied": bool, "objection": "..."}]
pub fn build_adversary_satisfaction_prompt(
    obligations: &[(
        &crate::models::dag::Obligation,
        Vec<crate::models::dag::ProofNode>,
    )],
    current_step_natural: &str,
    current_step_formal: Option<&str>,
    all_obligations: &[crate::models::dag::Obligation],
    solver_hint: &str,
    step_number: u32,
    enriched_context: &str,
) -> String {
    let mut p = String::from(
"You are an ADVERSARIAL REVIEWER. Your job is to find gaps and flaws in claimed obligation satisfaction.\n\
For each obligation below, prior verified steps are shown. The solver claims this work may satisfy the obligation.\n\
Your role: be skeptical. Look for:\n\
- Missing cases or edge cases not covered\n\
- Logical gaps between steps and the obligation's requirements\n\
- Unjustified leaps or unstated assumptions\n\
- Whether the formal expressions actually prove what's claimed\n\n\
IMPORTANT: Judge ONLY the verified steps shown below. Do NOT import answers or results from your training data.\n\
If you recognize this problem, ignore what you think the answer is. Evaluate only what the steps actually prove.\n\n\
If you genuinely believe the obligation IS satisfied by the cumulative work, say so. Don't be contrarian for its own sake.\n\
But if there's a real gap, identify it clearly.\n\n");

    // Enriched context (research, prior attempts, pattern stats)
    if !enriched_context.is_empty() {
        p.push_str(enriched_context);
        p.push('\n');
    }

    p.push_str(&format!(
        "CURRENT STEP NUMBER: {} (budget awareness)\n\n",
        step_number
    ));

    p.push_str(&format!("LATEST STEP: {}", current_step_natural));
    if let Some(formal) = current_step_formal {
        p.push_str(&format!(" [formal: {}]", formal));
    }
    p.push_str("\n\n");

    // Show closed obligations so the adversary knows what's already resolved
    let closed: Vec<&crate::models::dag::Obligation> = all_obligations
        .iter()
        .filter(|o| o.status != "open" && o.status != "assigned")
        .collect();
    if !closed.is_empty() {
        p.push_str(&format!(
            "ALREADY RESOLVED ({} obligations — not under review):\n",
            closed.len()
        ));
        for ob in closed.iter().take(6) {
            let status_label = match ob.status.as_str() {
                "closed_proved" => "PROVED",
                "closed_spurious" => "SPURIOUS",
                _ => "CLOSED",
            };
            p.push_str(&format!(
                "  [{}] [{}] {}\n",
                status_label, ob.obligation_type, ob.description
            ));
        }
        p.push_str("Only review the OPEN obligations below.\n\n");
    }

    // Solver's self-assessment (if it claims closure)
    if !solver_hint.is_empty() {
        p.push_str(solver_hint);
        p.push('\n');
    }

    for (i, (ob, nodes)) in obligations.iter().enumerate() {
        p.push_str(&format!(
            "OBLIGATION {}: [id={}] {}\n",
            i + 1,
            ob.id,
            ob.description
        ));
        p.push_str(&format!(
            "  Type: {}, Priority: {:.2}\n",
            ob.obligation_type, ob.priority
        ));
        if let Some(ref criteria) = ob.satisfaction_criteria {
            p.push_str(&format!("  Satisfaction criteria: {}\n", criteria));
        }

        let verified: Vec<_> = nodes.iter().filter(|n| n.status == "verified").collect();
        if verified.is_empty() {
            p.push_str("  Prior work: NONE\n");
        } else {
            p.push_str(&format!(
                "  Prior verified steps ({} total):\n",
                verified.len()
            ));
            // Show last 5 verified nodes
            for node in verified.iter().rev().take(5).rev() {
                let content_preview: String = node.content.chars().take(150).collect();
                let formal_str = node.formal_content.as_deref().unwrap_or("none");
                p.push_str(&format!(
                    "    - \"{}\"\n      [formal: {}]\n",
                    content_preview, formal_str
                ));
            }
        }
        p.push('\n');
    }

    p.push_str(
"Use your thinking phase to reason through each obligation's satisfaction criteria against the verified steps.\n\
Only after completing your analysis, output the JSON. Objection comes before verdict in your reasoning.\n\n\
Respond with ONLY a JSON array. For each obligation, fields in this order — objection before satisfied:\n\
- \"id\": the obligation id\n\
- \"objection\": your analysis — what's missing or wrong, or why it IS satisfied\n\
- \"satisfied\": true if you genuinely believe the cumulative work satisfies it, false if not\n\n\
Example: [{\"id\": \"abc-123\", \"objection\": \"Steps prove n>0 case but obligation requires all integers including n<=0\", \"satisfied\": false}]\n\
or [{\"id\": \"abc-123\", \"objection\": \"All three cases covered with formal verification\", \"satisfied\": true}]");

    p
}

/// Parse adversary satisfaction verdicts from JSON response.
/// Returns Vec<(obligation_id, satisfied, objection)>.
pub fn parse_adversary_satisfaction(response: &str) -> Vec<(String, bool, String)> {
    // Try to find JSON array in response (may have surrounding text)
    let text = response.trim();
    let json_start = text.find('[');
    let json_end = text.rfind(']');

    if let (Some(start), Some(end)) = (json_start, json_end) {
        if let Ok(arr) = serde_json::from_str::<Vec<serde_json::Value>>(&text[start..=end]) {
            return arr
                .iter()
                .filter_map(|v| {
                    let id = v.get("id")?.as_str()?.to_string();
                    let satisfied = v.get("satisfied")?.as_bool()?;
                    let objection = v
                        .get("objection")
                        .and_then(|o| o.as_str())
                        .unwrap_or("")
                        .to_string();
                    Some((id, satisfied, objection))
                })
                .collect();
        }
    }

    Vec::new()
}
